version: '3'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - '5432:5432'
    volumes:
      - ./db_creation.sql:/docker-entrypoint-initdb.d/1-init.sql